### ISSUE TITLE
Game refuses to start after launching.

### ISSUE THREAD

**Issue by m4n02** [TheComputerizer/Dimension-Hopper-The-Fall#5]
**Version**
Released V1.5.4

**Log**
https://mclo.gs/HC1BaP8

**Describe the issue**
Upon launching the client, the instance refuses to load, given some seconds. To further add, the ram usage freezes on the java instance, as seen on task manager.

**To Reproduce**
- Step 1: Initiate the Launcher via curseforge.
- Step 2: Click "Play".
- Step 3: Launcher closes, but game now doesn't load.

**Comment by TheComputerizer** [comment]
Remove unimixins from the.mods folder. Idk why CF exported it but it won't be in 1.5.5

**Comment by Kralicek94** [comment]
I have the same issue, but I don't have the unimixins mod in mods folder... Looked for the filename online and it was"+unimixins-all-", and some other numbers. The problem is that I have this file in the mods folder but it has ".jar.disabled" suffix on it so MC isn't loading the mod anyway (yes I tried removing it, didn't do anything). Any other fixes please ?

**Comment by m4n02** [comment]
I've removed the file as instructed, but the problem persists.

**Comment by TheComputerizer** [comment]
Migrating this issue to #9 since I wrote the fix there
